### PR TITLE
Show detailed info of availability on click!

### PR DESCRIPTION
**Pull request by sujunglee**
You can hover over each event to see which users can attend that time slot:

Screen Shot 2020-02-10 at 7 21 06 PM

Screen Shot 2020-02-10 at 7 21 11 PM

I'll add more styling to this later on so it looks a bit prettier

### CODE REVIEW

**Comment by sujunglee** [comment]
Screen Shot 2020-02-10 at 8 28 47 PM

**Comment by jbrain98** [comment]
hover doesnt seem to be working for me?

**Comment by sujunglee** [comment]
@jbrain98 Ah we ditched the hover thing (since it doesn't work on mobile). Now the availability should be displayed on the pop-up when you click on an event!

**Comment by sujunglee** [comment]
@jbrain98  Should look like this:

Screen Shot 2020-02-10 at 8 38 34 PM

**Pull request merged**
